name: dev-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - sympy
  - xlrd
  - openpyxl
  - plotly
  - bokeh
  - tqdm
  - dask
  - numba
  - cython
  - sqlalchemy
  - beautifulsoup4
  - requests
  - lxml
  - networkx
  - nltk
  - pyarrow
  - fastparquet
  - lightgbm
  - xgboost
  - tensorflow
  - keras
  - pytorch
  - transformers
  - spacy
  - pyyaml
  - black
  - flake8
  - pytest
  - mkl
  - pip
  - pyodbc
  - fastapi
  - uvicorn
  - pydantic
  - azure-identity
  - pip:
      - jupyterlab
      - notebook
      - jupyter-contrib-nbextensions
      - jupytext
      - ipywidgets
      - chart-studio
      - pandas-profiling
      - dash
